import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

export default function Home() {
  const [webSiteSetting, setWebSiteSetting] = useState({});

  async function getWebData(contactDetails) {
    const response = await fetch("/api/webdata", {
      method: "GET",
      body: JSON.stringify(contactDetails),
      headers: {
        "Content-Type": "application/json",
      },
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.message || "Something went wrong!");
    }

    setWebSiteSetting(data[0]);
  }
  useEffect(() => {
    getWebData();
  }, []);

  function LogData() {
    console.log(webSiteSetting);
  }

  return (
    <div className="container">
      <Head>
        <title>Wedding RSV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div>test header</div>
      </header>

      <main className="main">
        <div>
          <button onClick={LogData}>Log Data</button>
          <img
            src={`data:image/jpeg;base64,${webSiteSetting.heroimg}`}
            alt="Landscape picture"
          />
        </div>
      </main>

      <footer className="footer">
        <a target="_blank" rel="noopener noreferrer">
          All Right Reserve to Wundrful Sites
        </a>
      </footer>
    </div>
  );
}
