import Head from "next/head";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { getRemainingDate } from "../libs/web-util";

export default function Home(props) {
  const [time, setTime] = useState(1 * 24 * 3600 + 1 * 3600 + 1 * 60 + 1);

  const remainTime = useMemo(() => {
    const days = Math.floor(time / 24 / 3600);
    const hours = Math.floor((time - days * 24 * 3600) / 3600);
    const minutes = Math.floor((time - days * 24 * 3600 - hours * 3600) / 60);
    const seconds = (time - days * 24 * 3600 - hours * 3600) % 60;

    return {
      days,
      hours,
      minutes,
      seconds,
    };
  }, [time]);

  useEffect(() => {
    const interval = setInterval(() => {
      setTime((time) => (time !== 0 ? time - 1 : 0));
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  function LogData() {
    console.log(props);
    getRemainingDate(props.webSiteSetting);
  }

  return (
    <div className="container">
      <Head>
        <title>Wedding RSV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="main"
        style={{
          backgroundImage: `url(data:image/jpeg;base64,${props.webSiteSetting.heroimg})`,
        }}
      >
        <div>
          <Link href="/settings">to settings</Link>
          <button onClick={LogData}>Log Data</button>
          <p>
            {remainTime.days} {remainTime.hours} {remainTime.minutes}{" "}
            {remainTime.seconds}{" "}
          </p>
        </div>
      </main>
    </div>
  );
}
