import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import { TimerCard } from "../components";


export default function Home(props) {
  useEffect(() => {
    const interval = setInterval(() => {
      props.calRemaining();
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  function LogData() {
    console.log(props);
  }

  return (
    <div className="container">
      <Head>
        <title>Wedding RSV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="main"
        style={{
          backgroundImage: `url(data:image/jpeg;base64,${props.webSiteSetting.heroimg})`,
        }}
      >
        <div>
          <Link href="/settings">to settings</Link>
          <button onClick={LogData}>Log Data</button>
        </div>
        <div className="timer">
          <TimerCard title='years' time={props.remainingTime.years}/>
          <TimerCard title='months' time={props.remainingTime.months}/>
          <TimerCard title='days' time={props.remainingTime.days}/>
          <TimerCard title='hours' time={props.remainingTime.hours}/>
          <TimerCard title='minutes' time={props.remainingTime.minutes}/>
          <TimerCard title='seconds' time={props.remainingTime.seconds}/>
        </div>
      </div>
    </div>
  );
}
